private $arrayClientes = array(
        array(
            'id_cliente' => '30723058',
            'nom_cliente' => 'Marleny', 
            'ape_cliente' => 'Juajinoy España', 
            'tel_cliente' => '3206692168', 
            'email_cliente' => 'marleny@gmail.com', 
            'dir_cliente' => 'Carrera 1 #9-62',
        ),
        array(
            'id_cliente' => '12981540',
            'nom_cliente' => 'Juan', 
            'ape_cliente' => 'Calpa Delgado', 
            'tel_cliente' => '3128422316', 
            'email_cliente' => 'juandelgado@gmail.com', 
            'dir_cliente' => 'Carrera 23a #5-14',
        ),
        array(
            'id_cliente' => '1085123587',
            'nom_cliente' => 'Luis', 
            'ape_cliente' => 'Martinez Agreda', 
            'tel_cliente' => '3215345123', 
            'email_cliente' => 'luis@gmail.com', 
            'dir_cliente' => 'Carrera 14d #12-3',
        ),
        array(
            'id_cliente' => '1086543678',
            'nom_cliente' => 'Fernando', 
            'ape_cliente' => 'Diaz Benavides', 
            'tel_cliente' => '3172346412', 
            'email_cliente' => 'fernandob@gmail.com', 
            'dir_cliente' => 'Calle 12a #2-11',
        ),
        array(
            'id_cliente' => '1087234697',
            'nom_cliente' => 'Salomé', 
            'ape_cliente' => 'Goyes Paredes', 
            'tel_cliente' => '3183821342', 
            'email_cliente' => 'salomeg@gmail.com', 
            'dir_cliente' => 'Carrera 16b #8-25',
        ),
    );